language: ruby
cache: bundler
rvm:
- 2.3.1

before_script:
- chmod +x ./script/cibuild
script: "./script/cibuild"

deploy:
  skip_cleanup: true
  provider: script
  script: "./script/deploy"
  on:
    branch: master

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - secure: btlj2wVGGioUv+ELnygNUblPy7Ai8xa3Ldb3z4++cM5KUTQXICbs/5MeM+UQZWj/bh0X7XsLc05D5EmdMs8FdcwTnWHuEJc0rcMhn86JQYpxHTeJFu+f+CBkoDSlewl0IcQAWYL2Rs/9Y9t6IlV3z/SaVfv/r481gEYmVSJU9gPgmcnhchofawKvChiw7sj4etBqzwjFCUg6NHgmlUmaffPX/i2CvKFCeMuigGgPvliVL2g0LGBOb218aNYKLMYTxlFeUWCPYKw0rG94LvoUmn3BWlBgUhgB8c8rDJbR27FFUOP19TJCdfGVsI3THU1cfipCM+ecDlz2QqbyYSYlOouWKcVJkHXBvCoXYF7dUud8Z4BhNBd/bsYRdFZ1iAvNlp7VP3wQgMsW90QRrAkMrN8aOlhehk2pbfdJrnWw1hqXYLMMG6GDRaOoGo17C+5Z5M9w//ZVCiqtECz5KkIGu8WXay84uzSyQtnJ8sLFiuwu0tMq4m14/X5/suVH1K6wEHrIrXAHtlt8LD78xnb9L6ZMydcVerp2GTt8/ifFJAUqUUnD+bAzx2VbGlCNKUqlRZoH991WUSaKEwLJeoD4rBiqbI2FiKlKBeKz17tltyDW+sxbDpJt/NqimJnYlWV0cOMwyiWdUEgzQHxRxbjEu+9rNehmnBxnETG2glN5v3g=
  - GIT_DEPLOY_REPO: https://$GH_TOKEN@github.com/oncleben31/oncleben31.github.io.git
  - GIT_DEPLOY_BRANCH: master
sudo: false
