# Principal site configuration

title: Oncleben31.cc
description: > # this means to ignore newlines until "baseurl:"
  Les contributions à l'Open Source et les découvertes d'Oncleben31 partagées
  avec l'Internet mondial.
twitter_username: oncleben31
github_username:  oncleben31
google_analytics: UA-10458131-3
disqus:
  shortname: oncleben31-cc

### Basic i18n:
lang: fr
posts_title: "Articles"
subscribe_RSS: "S'abonner aux flux "


# Build settings
markdown: kramdown
theme: minima

#Jekyll settings
permalink: /:categories/:title/
exclude:
  - Gemfile
  - LICENSE
  - README
  - config
  - rakefile
  - script

gems:
 - jekyll-sitemap
