# Principal site configuration

title: Oncleben31.cc
description: > # this means to ignore newlines until "baseurl:"
  Les contributions à l'Open Source et les découvertes d'Oncleben31 partagées
  avec l'Internet mondial.
url: http://oncleben31.cc
twitter_username: oncleben31
github_username:  oncleben31
google_analytics: UA-10458131-3
disqus:
  shortname: oncleben31-cc

### Basic localisation (l10n)
# If you customize the lang parameter, minima will try to use the strings in _data/locales/[lang].yml
# Read https://github.com/jekyll/minima/README.md for more information.
lang: fr

# Even the day and month names will be translated. You can customize your date by
# uncommenting the following line and customizing the date format:
date_format: "Le %-d %B %Y"

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      author: oncleben31
      categories: article


# Build settings
markdown: kramdown
kramdown:
  input: GFM
  
theme: minima

#Jekyll settings
permalink: /:categories/:title/
exclude:
  - Gemfile
  - LICENSE
  - README
  - config
  - rakefile
  - script
  - vendor

gems:
 - jekyll-sitemap
 - jemoji
 - jekyll-last-modified-at
