# config for local testing
# use it with: bundle exec jekyll serve --host 0.0.0.0 --config _config.yml,_config_dev.yml

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
