# Principal site configuration

title: Oncleben31.cc
description: > # this means to ignore newlines until "baseurl:"
  Les contributions à l'Open Source et les découvertes d'Oncleben31 partagées
  avec l'Internet mondial.
twitter_username: oncleben31
github_username:  oncleben31
lang: fr

# Build settings
markdown: kramdown
theme: minima

#Jekyll settings
permalink: /:categories/:title/
exclude:
  - Gemfile
  - LICENSE
  - README
  - config
  - rakefile
